### ISSUE TITLE
Missing database

### ISSUE THREAD

**Issue by YoruTen** [MajorArkwolf/AgendaBot#1]
Hi
I was looking around for a bot that could help write agendas an I found this and thought it might be interesting. I set it up on a Raspberry Pi running Raspberry OS, have managed to get it to log in to the server but I'm having trouble with the database, it seams to create a file named serverinfo.db but this file seams empty when I open it with SQLite3. 
I get this error when trying to call the bot:
`sqlite3.OperationalError: no such table: server`

I know this haven't been updated in a while, but do you have an example db-file so I can get the structure? Or if the code could be update so that it creates a database with the correct structure if non exists.

**Comment by MajorArkwolf** [comment]
Hey @YoruTen

Yeah no problem I will fix that up for you :).

**Comment by MajorArkwolf** [comment]
Okay @YoruTen I have updated the repo with a setup folder and added instructions if this has fixed your problem or you no longer need this please go ahead and close the issue.

**Comment by YoruTen** [comment]
Hi @MajorArkwolf, thanks for the update, I'm not sure when I will have the time to test, but will come back when I have!
